version: "3.1"
services:
  web:
    build: ./app
    container_name: web
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cacti
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    ports:
      - 5005:5000
    depends_on:
       - db
    links:
     - db
  
  db:
    image: postgres:15.0
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cacti
      - POSTGRES_PORT=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5