version: "3.1"
services:
  web:
    image: logiczmaksimka/sber_devops:my_simple_web
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    depends_on:
      - db
    links:
     - db
  
  db:
    image: postgres:15.0
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cacti
      - POSTGRES_PORT=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always